version: '2'
services:
  test:
    image: node:latest
    working_dir: /app
    volumes:
      - .:/app
    command: >
      /bin/bash -c "
        ./wait-for-it.sh mysql:3306 -t 20
        npm run mocha;
      "
    depends_on:
      - mysql

  mysql:
    image: mysql
    environment:
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: ''
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
      - "3306:3306"
    restart: always
